//Nome: Henrique Cesar Nogarini de Carvalho   RA: 2102374
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.henrique.registroacademia.Telas.telaFuncionario;

import br.henrique.registroacademia.Academia;
import br.henrique.registroacademia.Cliente;
import br.henrique.registroacademia.Funcionario;
import br.henrique.registroacademia.GenCliente;
import br.henrique.registroacademia.GenFuncionario;
import br.henrique.registroacademia.NegativeException;
import br.henrique.registroacademia.Telas.FormAcademia;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nchen
 */
public class AtualizacaoF extends javax.swing.JFrame {

    private long rg;

    
    public AtualizacaoF(long rg) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Atualização Funcionário");
        this.rg = rg;
        insereTudo();
        fechar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btRG = new javax.swing.JLabel();
        btNome = new javax.swing.JLabel();
        btTel = new javax.swing.JLabel();
        btAtua = new javax.swing.JLabel();
        btTrab = new javax.swing.JLabel();
        btBairro = new javax.swing.JLabel();
        btCidade = new javax.swing.JLabel();
        btRua = new javax.swing.JLabel();
        btNumero = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        cidadeTextField = new javax.swing.JTextField();
        rgTextField = new javax.swing.JTextField();
        atuaTextField = new javax.swing.JTextField();
        telTextField = new javax.swing.JTextField();
        trabTextField = new javax.swing.JTextField();
        ruaTextField = new javax.swing.JTextField();
        numeroTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btCdastrar = new javax.swing.JButton();
        bairroTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btRG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btRG.setText("RG:");

        btNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btNome.setText("Nome:");

        btTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btTel.setText("Telefone:");

        btAtua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btAtua.setText("Área que Atua");

        btTrab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btTrab.setText("Temp de trab:");

        btBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btBairro.setText("Tempo de treino:");

        btCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btCidade.setText("Cidade:");

        btRua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btRua.setText("Rua:");

        btNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btNumero.setText("Número:");

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        rgTextField.setEditable(false);

        atuaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atuaTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATUALIZAÇÃO DE CADASTRO");
        jLabel1.setPreferredSize(new java.awt.Dimension(191, 22));

        btCdastrar.setText("ATUALIZAR");
        btCdastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCdastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairroTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cidadeTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btRG)
                                    .addComponent(btAtua))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(atuaTextField)
                                    .addComponent(rgTextField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btTel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btTrab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btRua, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btNumero, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telTextField)
                            .addComponent(trabTextField)
                            .addComponent(ruaTextField)
                            .addComponent(numeroTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeTextField)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 247, Short.MAX_VALUE)
                .addComponent(btCdastrar)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRG, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trabTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atuaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtua, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTrab, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRua, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btCdastrar)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atuaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atuaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atuaTextFieldActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void fechar(){
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                new FormFuncionario().setVisible(true);
                dispose();
            }    
        });
    }
    private void insereTudo(){
        Funcionario silvao = Academia.genrenciaF.getFuncionario(rg);
        if(silvao != null){
            nomeTextField.setText(silvao.getNome());
            rgTextField.setText(String.valueOf(silvao.getRG()));
            telTextField.setText(String.valueOf(silvao.getTelefone()));
            trabTextField.setText(String.valueOf(silvao.getTempoutil()));
            atuaTextField.setText(silvao.getAtua());
            ruaTextField.setText(silvao.getEndereco().getRua());
            cidadeTextField.setText(silvao.getEndereco().getCidade());
            numeroTextField.setText(String.valueOf(silvao.getEndereco().getNumero()));
            bairroTextField.setText(silvao.getEndereco().getBairro());
              
        }
    }
            
            
            
    private void btCdastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCdastrarActionPerformed
    try{
        if(!ruaTextField.getText().isEmpty() && !nomeTextField.getText().isEmpty() 
                && !trabTextField.getText().isEmpty() && !cidadeTextField.getText().isEmpty()
                && !rgTextField.getText().isEmpty() && !telTextField.getText().isEmpty() && !numeroTextField.getText().isEmpty() 
                && !atuaTextField.getText().isEmpty() && !bairroTextField.getText().isEmpty()){
            
            Funcionario funcionario= Academia.genrenciaF.getFuncionario(rg);
            GenFuncionario gerenciaFuncionario = Academia.genrenciaF;
            if(funcionario != null){
            
                funcionario.setNome(nomeTextField.getText());
                funcionario.setTelefone(Long.parseLong(telTextField.getText()));
                funcionario.setAtua(atuaTextField.getText());
                funcionario.setTempoutil(Integer.parseInt(trabTextField.getText()));
                funcionario.getEndereco().setCidade(cidadeTextField.getText());
                funcionario.getEndereco().setRua(ruaTextField.getText());
                funcionario.getEndereco().setBairro(bairroTextField.getText());
                funcionario.getEndereco().setNumero(Integer.parseInt(numeroTextField.getText()));
                
               
                if(gerenciaFuncionario.getFuncionario(funcionario.getRG()) != null){
                    gerenciaFuncionario.updateFuncionario(funcionario);
                    JOptionPane.showMessageDialog(null,"Atualização realizado com sucesso!","Atualizado",JOptionPane.INFORMATION_MESSAGE);
                    new FormAcademia().setVisible(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"RG não encontrado!","ERRO",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Um ou mais campos estão vazios !","ERRO",JOptionPane.ERROR_MESSAGE);
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Você digitou um número inválido !","ERRO",JOptionPane.ERROR_MESSAGE);
        }catch(NegativeException n){
            JOptionPane.showMessageDialog(null,"Números negativos são inválidos !","ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCdastrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atuaTextField;
    private javax.swing.JTextField bairroTextField;
    private javax.swing.JLabel btAtua;
    private javax.swing.JLabel btBairro;
    private javax.swing.JButton btCdastrar;
    private javax.swing.JLabel btCidade;
    private javax.swing.JLabel btNome;
    private javax.swing.JLabel btNumero;
    private javax.swing.JLabel btRG;
    private javax.swing.JLabel btRua;
    private javax.swing.JLabel btTel;
    private javax.swing.JLabel btTrab;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField numeroTextField;
    private javax.swing.JTextField rgTextField;
    private javax.swing.JTextField ruaTextField;
    private javax.swing.JTextField telTextField;
    private javax.swing.JTextField trabTextField;
    // End of variables declaration//GEN-END:variables
}
