//Nome: Henrique Cesar Nogarini de Carvalho   RA: 2102374
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.henrique.registroacademia.Telas.telaCliente;

import br.henrique.registroacademia.Academia;
import br.henrique.registroacademia.Cliente;
import br.henrique.registroacademia.GenCliente;
import br.henrique.registroacademia.NegativeException;
import br.henrique.registroacademia.Telas.FormAcademia;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nchen
 */
public class Atualizacao extends javax.swing.JFrame {

    private long rg;

    
    public Atualizacao(long rg) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Atualização Cliente");
        this.rg = rg;
        insereTudo();
        fechar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btRG = new javax.swing.JLabel();
        btNome = new javax.swing.JLabel();
        btTel = new javax.swing.JLabel();
        btPlano = new javax.swing.JLabel();
        btObj = new javax.swing.JLabel();
        btTreino = new javax.swing.JLabel();
        btPersonal = new javax.swing.JLabel();
        btPeso = new javax.swing.JLabel();
        btAltura = new javax.swing.JLabel();
        btGordura = new javax.swing.JLabel();
        btTeste = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        pesoTextField = new javax.swing.JTextField();
        rgTextField = new javax.swing.JTextField();
        tpTextField = new javax.swing.JTextField();
        ttTextField = new javax.swing.JTextField();
        telTextField = new javax.swing.JTextField();
        objTextField = new javax.swing.JTextField();
        altTextField = new javax.swing.JTextField();
        gordTextField = new javax.swing.JTextField();
        testeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbPersonal = new javax.swing.JComboBox<>();
        btCdastrar = new javax.swing.JButton();
        btBairro = new javax.swing.JLabel();
        btCidade = new javax.swing.JLabel();
        btRua = new javax.swing.JLabel();
        btNumero = new javax.swing.JLabel();
        cidadeTextField = new javax.swing.JTextField();
        bairroTextField = new javax.swing.JTextField();
        ruaTextField = new javax.swing.JTextField();
        numeroTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btRG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btRG.setText("RG:");

        btNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btNome.setText("Nome:");

        btTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btTel.setText("Telefone:");

        btPlano.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btPlano.setText("Tipo de Plano:");

        btObj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btObj.setText("Objetivo:");

        btTreino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btTreino.setText("Tempo de treino:");

        btPersonal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btPersonal.setText("Personal:");

        btPeso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btPeso.setText("Peso:");

        btAltura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btAltura.setText("Altura:");
        btAltura.setFocusCycleRoot(true);

        btGordura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btGordura.setText("%Gordura:");

        btTeste.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btTeste.setText("Tipo de teste:");

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        rgTextField.setEditable(false);

        tpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTextFieldActionPerformed(evt);
            }
        });

        ttTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATUALIZAÇÃO DE CADASTRO");
        jLabel1.setPreferredSize(new java.awt.Dimension(191, 22));

        cbPersonal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        cbPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPersonalActionPerformed(evt);
            }
        });

        btCdastrar.setText("ATUALIZAR");
        btCdastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCdastrarActionPerformed(evt);
            }
        });

        btBairro.setText("Bairro:");

        btCidade.setText("Cidade:");

        btRua.setText("Rua:");

        btNumero.setText("Número:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btRG)
                                            .addComponent(btPlano)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btTreino)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(ttTextField)
                                    .addComponent(rgTextField))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btTel)
                                            .addComponent(btObj)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btAltura))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btPeso)
                                    .addComponent(btPersonal)
                                    .addComponent(btBairro)
                                    .addComponent(btCidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bairroTextField)
                                    .addComponent(cidadeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pesoTextField)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btTeste, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btGordura, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btRua, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btNumero, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telTextField)
                            .addComponent(objTextField)
                            .addComponent(altTextField)
                            .addComponent(gordTextField)
                            .addComponent(testeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(ruaTextField)
                            .addComponent(numeroTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeTextField)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(btCdastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRG, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btObj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGordura, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRua, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ruaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btCdastrar)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpTextFieldActionPerformed

    private void ttTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttTextFieldActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void fechar(){
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                new FormCliente().setVisible(true);
                dispose();
            }    
        });
    }
    private void cbPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPersonalActionPerformed

    private void insereTudo(){
        Cliente noronha = Academia.gerenciaC.getCliente(rg);
        if(noronha != null){
            altTextField.setText(String.valueOf(noronha.getDadosCorporais().getAltura()));
            gordTextField.setText(String.valueOf(noronha.getDadosCorporais().getGordura()));
            nomeTextField.setText(noronha.getNome());
            objTextField.setText(noronha.getMeta().getObjetivo());
            pesoTextField.setText(String.valueOf(noronha.getMeta().getTempodetreino()));
            rgTextField.setText(String.valueOf(noronha.getRG()));
            telTextField.setText(String.valueOf(noronha.getTelefone()));
            testeTextField.setText(noronha.getDadosCorporais().getTipodeteste());
            tpTextField.setText(noronha.getTipodeplano());
            ttTextField.setText(String.valueOf(noronha.getMeta().getTempodetreino())); 
            cidadeTextField.setText(noronha.getEndereco().getCidade());
            ruaTextField.setText(noronha.getEndereco().getRua());
            bairroTextField.setText(noronha.getEndereco().getBairro());
            numeroTextField.setText(String.valueOf(noronha.getEndereco().getNumero()));
        }
    }
            
            
            
    private void btCdastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCdastrarActionPerformed
    try{
        if(!altTextField.getText().isEmpty() && !gordTextField.getText().isEmpty() && !nomeTextField.getText().isEmpty() 
                && !objTextField.getText().isEmpty() && !pesoTextField.getText().isEmpty()
                && !rgTextField.getText().isEmpty() && !telTextField.getText().isEmpty() && !testeTextField.getText().isEmpty() 
                && !tpTextField.getText().isEmpty() && !ttTextField.getText().isEmpty()&& !btCidade.getText().isEmpty()
                && !btRua.getText().isEmpty()&& !btBairro.getText().isEmpty()&& !btNumero.getText().isEmpty()){
            Cliente cliente = Academia.gerenciaC.getCliente(rg);
            GenCliente gerenciaCliente = Academia.gerenciaC;
            if(cliente != null){
            
                cliente.setNome(nomeTextField.getText());
                cliente.setTelefone(Long.parseLong(telTextField.getText()));
                cliente.setTipodeplano(tpTextField.getText());
                cliente.getMeta().setObjetivo(objTextField.getText());
                cliente.getMeta().setTempodetreino(Float.parseFloat(ttTextField.getText().replace(",", ".")));
                cliente.getDadosCorporais().setAltura(Float.parseFloat(altTextField.getText().replace(",", ".")));
                cliente.getDadosCorporais().setPeso(Float.parseFloat(pesoTextField.getText().replace(",", ".")));
                cliente.getDadosCorporais().setGordura(Float.parseFloat(gordTextField.getText().replace(",", ".")));
                cliente.getDadosCorporais().setTipodeteste(testeTextField.getText());
                cliente.getEndereco().setCidade(cidadeTextField.getText());
                cliente.getEndereco().setRua(ruaTextField.getText());
                cliente.getEndereco().setBairro(bairroTextField.getText());
                cliente.getEndereco().setNumero(Integer.parseInt(numeroTextField.getText()));
                
                if(cbPersonal.getSelectedIndex() == 1){
                    cliente.getMeta().setPersonal(false);
                }
                else{
                    cliente.getMeta().setPersonal(true);
                }
                if(gerenciaCliente.getCliente(cliente.getRG()) != null){
                    gerenciaCliente.updateCliente(cliente);
                    JOptionPane.showMessageDialog(null,"Atualização realizado com sucesso!","Atualizado",JOptionPane.INFORMATION_MESSAGE);
                    new FormAcademia().setVisible(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"RG não encontrado!","ERRO",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Um ou mais campos estão vazios !","ERRO",JOptionPane.ERROR_MESSAGE);
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Você digitou um número inválido !","ERRO",JOptionPane.ERROR_MESSAGE);
        }catch(NegativeException n){
            JOptionPane.showMessageDialog(null,"Números negativos são inválidos !","ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCdastrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altTextField;
    private javax.swing.JTextField bairroTextField;
    private javax.swing.JLabel btAltura;
    private javax.swing.JLabel btBairro;
    private javax.swing.JButton btCdastrar;
    private javax.swing.JLabel btCidade;
    private javax.swing.JLabel btGordura;
    private javax.swing.JLabel btNome;
    private javax.swing.JLabel btNumero;
    private javax.swing.JLabel btObj;
    private javax.swing.JLabel btPersonal;
    private javax.swing.JLabel btPeso;
    private javax.swing.JLabel btPlano;
    private javax.swing.JLabel btRG;
    private javax.swing.JLabel btRua;
    private javax.swing.JLabel btTel;
    private javax.swing.JLabel btTeste;
    private javax.swing.JLabel btTreino;
    private javax.swing.JComboBox<String> cbPersonal;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JTextField gordTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField numeroTextField;
    private javax.swing.JTextField objTextField;
    private javax.swing.JTextField pesoTextField;
    private javax.swing.JTextField rgTextField;
    private javax.swing.JTextField ruaTextField;
    private javax.swing.JTextField telTextField;
    private javax.swing.JTextField testeTextField;
    private javax.swing.JTextField tpTextField;
    private javax.swing.JTextField ttTextField;
    // End of variables declaration//GEN-END:variables
}
