//Nome: Henrique Cesar Nogarini de Carvalho   RA: 2102374

package br.henrique.registroacademia.Telas.telaCliente;

import br.henrique.registroacademia.Academia;
import br.henrique.registroacademia.GenCliente;
import br.henrique.registroacademia.Telas.FormAcademia;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nchen
 */
public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btImpremetudo = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente Academia");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btImpremetudo.setText("Listar Todos");
        btImpremetudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImpremetudoActionPerformed(evt);
            }
        });

        btRemove.setText("Remover");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btImpremetudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btCadastrar)
                .addGap(18, 18, 18)
                .addComponent(btAtualizar)
                .addGap(18, 18, 18)
                .addComponent(btImpremetudo)
                .addGap(18, 18, 18)
                .addComponent(btRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
       new Cadastro().setVisible(true);
       dispose();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        String escolheRG = JOptionPane.showInputDialog(null,"Digite o RG que deseja atualizar","Atualização",JOptionPane.QUESTION_MESSAGE);
        GenCliente clienteX = Academia.gerenciaC;
        if(escolheRG != null){
            try{
                long e = Long.parseLong(escolheRG);
                if(clienteX.getCliente(e) != null){
                   new Atualizacao(e).setVisible(true);
                   dispose(); 
                }
                else{
                    JOptionPane.showMessageDialog(null,"RG não existente","ERRO",JOptionPane.ERROR_MESSAGE);
                }

            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Número Digitado Inválido !");
            }
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
       String escolheRG = JOptionPane.showInputDialog(null,"Digite o RG que deseja remover","Remoção",JOptionPane.QUESTION_MESSAGE);
        if(escolheRG != null){
            try{
                GenCliente clienteRemove = Academia.gerenciaC;
                long e = Long.parseLong(escolheRG);
                if(clienteRemove.getCliente(e) != null){
                    clienteRemove.removeCliente(e);
                    JOptionPane.showMessageDialog(null,"Cliente removido com sucesso!","Remover",JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Esse RG não existe !!","ERRO",JOptionPane.ERROR_MESSAGE);
                }
                
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Número Digitado Inválido !");
            }
        }
    }//GEN-LAST:event_btRemoveActionPerformed

    private void btImpremetudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImpremetudoActionPerformed
        new Lista().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btImpremetudoActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        new FormAcademia().setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btImpremetudo;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btVoltar;
    // End of variables declaration//GEN-END:variables
}
